# Generated by Django 5.1.4 on 2025-05-15 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studyroom',
            name='image',
            field=models.ImageField(blank=True, help_text='Image of the study room', null=True, upload_to='study_room_images/'),
        ),
    ]
